import{a as v,i as u,S as I}from"./assets/vendor-BDaiwwc1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const $="48409892-84416e27ee3da12ba614fc4d7",C=document.getElementById("fetch-btn");async function f(t,o){const n={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{const a=await v.get("https://pixabay.com/api/",{params:n});return C.style.display="block",a.data}catch(a){console.log(a)}}const E=document.querySelector(".gallery"),S=document.getElementById("fetch-btn");let w=0;const q=t=>{const{hits:o}=t;return w=t.totalHits,o.length===0&&(S.style.display="none",u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",backgroundColor:"red",close:!1,progressBar:!1})),o.map(({webformatURL:n,largeImageURL:a,tags:r,likes:s,views:i,comments:L,downloads:B})=>`
            <div class="image-card">
                <a href="${a}" target="_blank">
                    <img src="${n}" alt="${r}" loading="lazy" />
                </a>
                <div class="image-info">
                    <p><strong>Likes</strong> ${s}</p>
                    <p><strong>Views</strong> ${i}</p>
                    <p><strong>Comments</strong> ${L}</p>
                    <p><strong>Downloads</strong> ${B}</p>
                </div>
            </div>`).join("")},m=t=>{const o=q(t);E.insertAdjacentHTML("beforeend",o)},p=document.querySelector("form"),y=document.querySelector(".gallery"),d=document.getElementById("fetch-btn");let c="",l=1,g;function D(){p.addEventListener("submit",async t=>{t.preventDefault();//! loading span
if(d.insertAdjacentHTML("beforebegin","<span class='loader'></span>"),c=new FormData(t.target).get("search-input"),!c){u.show({message:"Input is empty!",messageColor:"white",position:"topRight",backgroundColor:"red",close:!1,progressBar:!1});return}p.reset(),l=1;try{const n=await f(c,l);y.innerHTML="",m(n),b(),h()}catch(n){console.error("Error:",n),y.innerHTML=""}}),d.addEventListener("click",async()=>{l+=1;try{const t=await f(c,l);m(t),b(),h(),H()}catch{console.error("Error:",e)}})}//! Scrolling
function H(){const t=document.querySelector(".image-card");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}//! End of scrolling
function h(){document.querySelectorAll(".image-card").length>=w?(u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",position:"topRight",backgroundColor:"blue",close:!1,progressBar:!1}),d.style.display="none"):d.style.display="block"}function b(){g&&g.destroy(),g=new I(".gallery a",{captionDelay:250}),g.refresh()}D();
//# sourceMappingURL=index.js.map
